applications/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "blog_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ), 
    path(
        'entrada/<pk>', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ), 
]

applications/favoritos/urls.py
#
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/', 
        views.UserPageListView.as_view(),
        name='perfil',
    ),
    path(
        'add-entrada/<pk>/', 
        views.AddFavoritosView.as_view(),
        name='add-favoritos',
    ),
    path(
        'delete-favorites/<pk>/', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favoritos',
    ),
]

applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'user/register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'user/logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'user/update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    #urls CKEDITOR
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/favorites/base_favorites.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/favorites/perfil.html
<!-- head para PC -->
{% extends "favorites/base_favorites.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center" style="margin-top: 1em;">
        <!-- bloque de datos de usuario -->
        <div class="cell small-12 large-4">
            <div class="callout">
                <h5>{{ user.full_name }}</h5>
                <p>{{ user.email }} - {{ user.ocupation }} - {{ user.date_birth }}</p>
                <a href="#">Editar Datos</a>
                <p>
                    <a href="{% url 'users_app:user-logout' %}" class="clear button secondary">Salir</a>
                </p>
            </div>
        </div>
        <!-- FIN bloque de datos de usuario -->


        <!-- bloque de articulos favoritos de usuario -->
        <div class="cell large-8 grid-x grid-margin-x align-center">
            
            {% for entrada in entradas_user %}
            <div class="cell small-12">
                <div class="card-favoritos">
                    <img class="card-favoritos-img" src="{{ entrada.entry.image.url }}" style="width: 200px;">
                    <div class="card-favoritos-body">
                        <h3 class="card-favoritos-body-titulo">{{ entrada.entry.title }}</h3>
                        <p class="card-favoritos-body-text">{{ entrada.entry.resume }}</p>
                        <form class="card-favoritos-body-actions" method="POST" action="{% url 'favoritos_app:delete-favoritos' entrada.id %}"> {% csrf_token %}
                            <a class="button warning" href="{% url 'blog_app:entry-detail' entrada.entry.id %}">Ver</a>
                            <button type="submit" class="button alert" >Eliminar</button>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- FIN bloque de articulos favoritos de usuario -->
    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}